### ISSUE TITLE
Removing kernel parameter requires its value to be specified

### ISSUE THREAD

**Issue by bparry02** [linux-system-roles/bootloader#123]
Hello,

When attempting to remove a kernel parameter using the bootloader role, I noticed that it wasn't working. I discovered that since the parameter specified a value of `1`, I needed to provide its current value as part of the kernel options variable. Once I specified the kernel paramter name *and* it's value, the role removed it from the grub config correctly.

If this behavior is expected, then it should be documented as an example in the README.

## Desired behavior

When removing a kernel parameter by specifying `state: absent`, I should not have to also specify its value. This matches the behavior of `grubby --update-kernel=ALL --remove-args=print-fatal-signals` and better aligns with ansible conventions in other modules (e.g. ansible.builtin.file).

```
- name: Update bootloader to remove parameter
  vars:
    bootloader_settings:
      - kernel: ALL
        options:
          - name: print-fatal-signals
            state: absent
    bootloader_reboot_ok: true
  ansible.builtin.import_role:
    name: fedora.linux_system_roles.bootloader
```

On the managed host, `grubby --info ALL` should show the parameter has been removed.

## Actual behavior

On the managed host, when the parameter value is not specified in bootloader_settings, then `grubby --info ALL` shows the parameter is still present.

## Workaround

When a kernel parameter's value is also specified as part of bootloader_settings, the role will remove the parameter properly:

```
- name: Update bootloader to remove parameter
  vars:
    bootloader_settings:
      - kernel: ALL
        options:
          - name: print-fatal-signals
            value: 1
            state: absent
    bootloader_reboot_ok: true
  ansible.builtin.import_role:
    name: fedora.linux_system_roles.bootloader
```

## Environment

Control node:
```
$ ansible --version
ansible [core 2.15.12]
  python version = 3.12.7 (main, Oct  1 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/usr/bin/python3)

$ pip list --user | grep ansible
ansible                   8.7.0
ansible-compat            24.8.0
ansible-core              2.15.12
ansible-lint              24.7.0

$ ansible-galaxy collection list | grep fedora
fedora.linux_system_roles                1.88.7
```

Managed node:
```
# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```
